create database blockchain;
use blockchain;
call adduser(1, 'Rohan');
call adduser(2, 'Snehangsu');
call adduser(3, 'Rishabh');
insert into transaction_type values(1, 'CryptoCurrency');
call transaction_add(1,1,2,'Request', 'Rohan Requested for 30 Rs');
call transaction_add(2,2,1,'Paid', 'Snehangsu paid Rohan 30 Rs');
call transaction_add(3,3,1,'Requseted', 'Rishabh requested for 1000');
call transaction_add(4,1,3,'Paid', 'Rohan Paid Rishabh 1000 Rs');
call transaction_add(5,1,2,'Owes', 'Rohan owes Snehangsu 30 Rs');
call transaction_add(6,1,3,'Owes', 'Rishabh owes Rohan 1900 Rs');
call block_add(1);
call block_mine(7, 1);
call block_add(2);
call block_mine(6, 2);
call block_add(3);
call block_mine(5, 3);
call block_add(4);
call block_mine(4, 4);
call block_add(5);
call block_mine(4, 5);
call block_add(6);
call block_mine(3, 6);
update block as b inner join transaction as t on b.block_id=t.transaction_id set b.block_hash=t.transaction_hash;
update block as b inner join block as c on b.prev_block_id=c.block_id set b.prev_block_hash=c.block_hash;
select * from user;
select * from message;
select * from transaction;
select * from block;